apiVersion: k8s.sandstorm.de/v1alpha1
kind: OneContainerOnePort
metadata:
  name: excalidraw
spec:
  image: excalidraw/excalidraw:latest
  port: 80
  hostNames:
    excalidraw.${BASE_DOMAIN}: []
  replicas: 1
  ssl: true
  stagingCertificates: true
  healthChecks:
    startupProbe:
      enabled: true
    readinessProbe:
      enabled: true
    livenessProbe:
      enabled: true
