---
- name: Deploy cert-manager and Rancher as auto-deployed Helm charts
  template:
    src: "{{ item.src }}"
    dest: "/var/lib/rancher/k3s/server/manifests/{{ item.dest }}"
  loop:
    - { src: "certmanager-helm.yml.j2", dest: "certmanager-helm.yml" }
    - { src: "rancher-helm.yml.j2", dest: "rancher-helm.yml" }
  notify:
    - restart k3s
