# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/k8s.sandstorm.de_databases.yaml
- bases/k8s.sandstorm.de_databaseservers.yaml
# +kubebuilder:scaffold:crdkustomizeresource
