apiVersion: k8s.sandstorm.de/v1alpha1
kind: Database
metadata:
  labels:
    app.kubernetes.io/name: operator-database
    app.kubernetes.io/managed-by: kustomize
  name: example-database
spec:
  databaseServer: postgres1
