apiVersion: v1
kind: Namespace
metadata:
  name: operator-database-system
---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ mariadb_operator_server_name }}'
  namespace: operator-database-system
data:
  admin_password: '{{ mariadb_root_password | b64encode }}'
